DROP TABLE IF EXISTS Employee CASCADE; 

DROP TABLE IF EXISTS Planner CASCADE;

DROP TABLE IF EXISTS Task CASCADE;

DROP TABLE IF EXISTS Plan CASCADE;

DROP TABLE IF EXISTS Qualification CASCADE;

DROP TABLE IF EXISTS Block CASCADE;