DROP TABLE IF EXISTS Employee CASCADE; 

DROP TABLE IF EXISTS Planner CASCADE;

DROP TABLE IF EXISTS Task CASCADE;

DROP TABLE IF EXISTS Plan CASCADE;

DROP TABLE IF EXISTS Qualification CASCADE;

DROP TABLE IF EXISTS Weekday CASCADE;

DROP TABLE IF EXISTS Week CASCADE;

DROP TABLE IF EXISTS Weeks CASCADE;

DROP TABLE IF EXISTS DateOfTask CASCADE;

DROP TABLE IF EXISTS PlanBlock CASCADE;